### PR TITLE
Create Art Module

### PR DESCRIPTION
**Pull request by ooigheehong**

### CODE REVIEW

**Comment by ansen5007** [comment]
i think nothing much to add in. it is more than enough. @ooigheehong

**Comment by wczhen** [comment]
For me, i  think there is noting much to suggest on this module.

**Comment by Bokcheeaun** [comment]
So in this art module is all about entering coming artist's details right? Like artist name, address , ic number and etc...

**Comment by ansen5007** [comment]
Oh yeah, I think the art module need to link with artist to prevent art to link with wrong artist

**Comment by ooigheehong** [comment]
Thanks for the suggestion

**Pull request closed without merging**
