### PR TITLE
Ticketing Module

### PR DESCRIPTION
**Pull request by Bokcheeaun**

### CODE REVIEW

**Comment by Bokcheeaun** [comment]
This is the ticket module to allow customer to purchase ticket to enter the exhibition.

**Comment by ooigheehong** [comment]
the ticketing can based on the schedule to product ticket?

**Comment by Bokcheeaun** [comment]
Yes the staff need to select which exhibition schedule in order to generate that particular date ticket to customer.

**Comment by ooigheehong** [comment]
how do the calculation of the ticket?

**Comment by wczhen** [comment]
Each ticket have their own ticket ID?

**Comment by ooigheehong** [comment]
do ticket can get any member discount?

**Comment by ansen5007** [comment]
i agree with @ooigheehong .
@Bokcheeaun  any additional charge for ticket ？ i think u must have a clear and standard calculation that must including the tax

**Comment by Bokcheeaun** [comment]
@ooigheehong The calculation is based on the member type which is member or non-member and the total number of ticket had purchased.

**Comment by Bokcheeaun** [comment]
@wczhen Yes each ticket has its own ID

**Comment by Bokcheeaun** [comment]
@ansen5007 The ticket price is including good and service tax 6%

**Pull request closed without merging**
