### PR TITLE
Function of Membership

### PR DESCRIPTION
**Pull request by ansen5007**

### CODE REVIEW

**Comment by ansen5007** [comment]
Guys, i draft out the simple code. Any info of the customer can store inside ?

**Comment by Bokcheeaun** [comment]
Should we include the customer's debit card number? So that when they purchase art during the exhibition can use debit card to pay for it.

**Comment by ansen5007** [comment]
that is the critical information, alright . Noted

**Comment by wczhen** [comment]
I think we should include the member's Date of Birth so that the registered member can entitle their promotion such as discount for purchasing exhibition ticket.

**Comment by ooigheehong** [comment]
@Bokcheeaun i think do not need to save the card number, just process when customer purchase item or ticket

**Comment by ansen5007** [comment]
@wczhen  Noted

**Comment by ansen5007** [comment]
yes. @ooigheehong  is right. No need saved the debit card number. But we need them to fill in the debit card number when they want purchase via debit card or credit card

**Comment by wczhen** [comment]
@ansen5007 you miss out something, for creating new membership personal details, the data should include username and password in order to let the user login to the system. But when displaying the information, the sensitive data (password) is an unnecessary data to display out.

**Comment by Bokcheeaun** [comment]
@wczhen  Yes it must have unique password for each member

**Comment by ooigheehong** [comment]
@wczhen we are not do online, customer does not need to login to purchase item. They buy directly in spot.

**Comment by ansen5007** [comment]
@wczhen  our system is offline. The user name and password are unnecessary part.

**Comment by ansen5007** [comment]
@Bokcheeaun Wake up please. our system is offline.

**Comment by ooigheehong** [comment]
@Bokcheeaun we are not doing the online system

**Comment by wczhen** [comment]
Well, ok now i get it. How many percent rate will be provided for the ticket discount?

**Comment by ansen5007** [comment]
i suggest 10% rate for ticket discount. agree?

**Comment by ooigheehong** [comment]
@ansen5007 for everyone?

**Comment by ansen5007** [comment]
10% rate just for those membership.

**Comment by wczhen** [comment]
Yes, I'm agree with you guys

**Comment by Bokcheeaun** [comment]
I agree that 10% is a optimum percentage for discount. If lesser than more 10% then it will be too much discount rate.

**Comment by ansen5007** [comment]
the rest i will handle it, thanks

**Comment by Bokcheeaun** [comment]
Okay wait for your good news

**Comment by ooigheehong** [comment]
ok, now i will close the case.

**Pull request closed without merging**
