### PR TITLE
Create Staff Module

### PR DESCRIPTION
**Pull request by Bokcheeaun**
Any more requirement needed to add in?

### CODE REVIEW

**Comment by ansen5007** [comment]
@Bokcheeaun what is the function u have inside this module?

**Comment by wczhen** [comment]
Is there any roles can be choose while creating new staff account.

**Comment by Bokcheeaun** [comment]
@wczhen Manager and staff

**Comment by Bokcheeaun** [comment]
Only Manager has the authority to modify staff's details.

**Comment by Bokcheeaun** [comment]
@ansen5007  Create new staff, receive existing staff, update existing staff's details, and delete existing staff.

**Comment by ooigheehong** [comment]
need to add username and password in staff module?

**Comment by ansen5007** [comment]
i think the username and password function are required in the system. what is your view? @Bokcheeaun

**Comment by wczhen** [comment]
We cannot delete the staff information, so i think we should remove the delete existing staff by replacing it with update the status of staff to deactivate within the update existing staff's details function. Do you guys all agree with that?

**Comment by Bokcheeaun** [comment]
@ansen5007 Sure I will add in later on

**Comment by ansen5007** [comment]
@wczhen AGREE.

**Comment by Bokcheeaun** [comment]
@wczhen  @ansen5007 In this system we are not allow non staff member which no longer work under the company to use the system. If we keep their details, they are still able to access the system with their username and password which will violate the company rules.

**Comment by wczhen** [comment]
Okay then. All the functions will remain the same as usual.

**Comment by ooigheehong** [comment]
i agree with that, we can do the security module separately from staff module. so that we can remove the username and password to secure our system. we also can delete staff record after several years

**Comment by ooigheehong** [comment]
so, @Bokcheeaun u create staff module with separate security module to protect our system

**Comment by wczhen** [comment]
When retrieving the staff information, what kind of details will be displayed? Will it include the username and password of the account.

**Comment by Bokcheeaun** [comment]
@wczhen Username and password will not be display when retrieving the staff's details

**Comment by ansen5007** [comment]
ya. Agree @Bokcheeaun.

**Comment by wczhen** [comment]
ok

**Pull request closed without merging**
