### PR TITLE
Wong Chia Zhen PA

### PR DESCRIPTION
**Pull request by wczhen**
//variables
char artID;
char artDesc;
char artistName;
double price;
double payment;
double payback;
double gst = 0.06;

//search for art
printf("Please Enter ART ID: ");
scanf("%s", artID);

//display brief art summary
printf("%s\n %s \n %s \n %s \n%.2lf", artID,artDesc,artistName,price);

//receive total payment amount
printf("Please Enter Payment Amount: ");
scanf("%s",payment);

//generate receipt
payback = price - payment;
printf("%s\n %s \n %s \n %s \n%.2lf \n%.2lf \n%.2lf \n%.2lf", artID,artDesc,artistName,price,price*gst, payment, payback);

### CODE REVIEW

**Comment by wczhen** [comment]
Do you guys have any suggestions for extra features to add in?

**Comment by ooigheehong** [comment]
i think we should provide member ID to have discount for member

**Comment by wczhen** [comment]
@ooigheehong ok noted

**Comment by ansen5007** [comment]
about the calculation, should we add in the gst inside?

**Comment by wczhen** [comment]
@ansen5007 Yes, i almost forgot. I will add the gst calculation inside it later

**Pull request closed without merging**
