### PR TITLE
Create Schedule

### PR DESCRIPTION
**Pull request by ooigheehong**

### CODE REVIEW

**Comment by wczhen** [comment]
The schedule time is manually assign?

**Comment by ooigheehong** [comment]
about the schedule, we do have assign time into it. it is just about date , venue, and artist

**Comment by Bokcheeaun** [comment]
If the date of schedule has over, will it still appear to allow the staff to pick?

**Comment by ooigheehong** [comment]
currently yes, but i will make changes of this

**Comment by ansen5007** [comment]
@ooigheehong  what is vanue u mentioned just now ?

**Comment by wczhen** [comment]
VENUE

**Comment by ooigheehong** [comment]
venue means like location, we just mention about the the building like TARUC DK5, Stapak Mall Centre @ansen5007

**Comment by wczhen** [comment]
you mean the schedule is manually enter by the staff and not auto generated by the system?

**Comment by Bokcheeaun** [comment]
The schedule will show how many ticket are still available for purchase right? Like the schedule on 7/5/2017 has an exhibition of 30 ticket available for purchase, if a person has bought 2 ticket so will the system show only 28 ticket left for purchase in the next  purchase.

**Comment by ooigheehong** [comment]
yes

**Comment by Bokcheeaun** [comment]
@wczhen I think the schedule date is manually key in by the staff not automated.

**Comment by ooigheehong** [comment]
@Bokcheeaun no, schedule do not have limit the tickets.

**Comment by ansen5007** [comment]
LOL. @ooigheehong  that is VENUE not VANUE.

**Comment by ooigheehong** [comment]
when did i type vanue?

**Comment by Bokcheeaun** [comment]
@ooigheehong  So you mean the exhibition allow unlimited ticket to purchase?

**Comment by ansen5007** [comment]
@ooigheehong  check your previous message

**Comment by ooigheehong** [comment]
@ansen5007 no

**Comment by Bokcheeaun** [comment]
@ooigheehong I misunderstood the quantity of ticket available to purchase should be apply at the ticketing module not in this schedule module. :smile:

**Comment by ooigheehong** [comment]
@Bokcheeaun no problem

**Pull request closed without merging**
