### PR TITLE
System Modules and Functions

### PR DESCRIPTION
**Pull request by ooigheehong**

### CODE REVIEW

**Comment by ansen5007** [comment]
what module should we provide into the system ?

**Comment by ooigheehong** [comment]
First we need to provide art and artist module to store the information of the Art and artist.

**Comment by wczhen** [comment]
Is there any other modules that we can add in to the system?

**Comment by ansen5007** [comment]
Sound good ! we can place the create retrieve update delete function inside this both module =D

**Comment by Bokcheeaun** [comment]
What should we include in the Artist Module? Can briefly explain the module function?

**Comment by ooigheehong** [comment]
mainly need to include basic CRUD function. about the art and artist i think we can put together because art is the master piece of artist

**Comment by ansen5007** [comment]
By the way , what is the official requirement to our system ? ,

**Comment by Bokcheeaun** [comment]
Every art's information need to contain the specific artist name that owns the art masterpiece right? So that we can keep track every artist's masterpiece.

**Comment by wczhen** [comment]
Other than CRUD functions, is there any other extra features we can add in to system?

**Comment by Bokcheeaun** [comment]
@ansen5007 @wczhen I think is CRUD functions and PROCUREMENT function. For the procurement function, the system allow customer to buy art from an exhibition.

**Comment by ooigheehong** [comment]
@wczhen now we focus on the module and function 1st, after that will discuss about feature

**Comment by ooigheehong** [comment]
besides that, i think the system also included the staff module and membership module

**Comment by wczhen** [comment]
When displaying the art masterpiece, the price should include inside it.

**Comment by ooigheehong** [comment]
erm... we need to divide the module to everyone. who will take 1st

**Comment by ansen5007** [comment]
@ooigheehong  Please allocate the task to me. =)

**Comment by ansen5007** [comment]
@ooigheehong  i can handle the membership module

**Comment by wczhen** [comment]
So i think we should have FIVE modules MEMBERSHIP, ART&ARTIST, STAFF, PURCHASE EXHIBITION TICKET and PURCHASE ART.

**Comment by ooigheehong** [comment]
exhibition ticket module... i think we need to do schedule to in order to generate the ticket

**Comment by ooigheehong** [comment]
should we need to do report?

**Comment by ansen5007** [comment]
@ooigheehong I don't think we should include the report module inside the system.

**Comment by ooigheehong** [comment]
well... ok @ansen5007

**Comment by ooigheehong** [comment]
so who wan to handle which part?

**Comment by Bokcheeaun** [comment]
@ansen5007 I agree to ansen because we need to ensure the system functional requirement must be included in the system first then only add more feature if there is extra time period.

**Comment by wczhen** [comment]
hmmm, I din't think of that. 
Good idea.
I'm agree with the schedule idea for generate ticket, since there might be many exhibition in different times.

**Comment by ansen5007** [comment]
U KEEP BLOWINGＦＵＣＫＥＲ

**Comment by wczhen** [comment]
Let me allocate the tasks to all of you.

1. @Bokcheeaun BOK CHEE AUN - handle STAFF and PURCHASE EXHIBITION TICKET module
2. @ooigheehong  OOI GHEE HONG - handle ART&ARTIST and SCHEDULE module
3. @ansen5007 WAN CHUN FATT - handle MEMBERSHIP module
4. WONG CHIA ZHEN - handle PURCHASE ART module

**Comment by ansen5007** [comment]
@wczhen  Noted

**Pull request closed without merging**
