### PR TITLE
Create Artist Module

### PR DESCRIPTION
**Pull request by ooigheehong**
this is the artist module which consist of CRUD function

### CODE REVIEW

**Comment by Bokcheeaun** [comment]
Do we need a special ID for each artist?

**Comment by wczhen** [comment]
Yes, of course we need it. So that it is easier to identify the artist. And also, it will be the Unique Key in order to eliminate the duplicate artist exist within the database.

**Comment by wczhen** [comment]
I thought this module should be ART and ARTIST isn't it?

**Comment by ooigheehong** [comment]
@wczhen yeah. but first, i need to finish artist module because art module is link to artist

**Comment by ansen5007** [comment]
@ooigheehong any function or feature inside the ARTIST module? Both module are same function ?

**Comment by ooigheehong** [comment]
@ansen5007 for the artist module i do not include art information which i will create another module for storing art data. artist module more likely to be same as staff and membership

**Comment by wczhen** [comment]
so the artist have the privilege to log in to the system?

**Comment by ooigheehong** [comment]
no, this system just only available for staff @wczhen

**Comment by Bokcheeaun** [comment]
How is the currently progress ?

**Comment by ooigheehong** [comment]
currently now is doing the artist module, after that will move on art module for linking to artist module

**Comment by ansen5007** [comment]
OKAY. GOOD LUCK !! @ooigheehong

**Pull request closed without merging**
